site_name: gitops-atlantis-poc
site_description: 'Main documentation for the gitops-atlantis-poc'
repo_url: https://github.com/jeitto/gitops-atlantis-poc

edit_uri: edit/main/docs

plugins:
  - techdocs-core
nav:
  - Overview:
      - Getting started: 'index.md'