repos:
  - id: github.com/marcelo-luizz/terraform-example
    apply_requirements: [mergeable]
    allowed_overrides: [workflow, apply_requirements]
    allow_custom_workflows: true
    workflow: terragrunt-workflow
    pre_workflow_hooks:
      - run: echo "Running pre-workflow hook for repo $REPO_NAME"
    post_workflow_hooks:
      - run: echo "Running post-workflow hook for repo $REPO_NAME"

workflows:
  terragrunt-workflow:
    plan:
      steps:
      - run: terragrunt init --terragrunt-non-interactive $COMMENT_ARGS
      - run: terragrunt plan -out=$PLANFILE --terragrunt-non-interactive $COMMENT_ARGS
    apply:
      steps:
      - run: terragrunt apply $PLANFILE --terragrunt-non-interactive $COMMENT_ARGS