repos:
  - id: github.com/marcelo-luizz/terraform-example
    workflow: terragrunt-workflow # Força o uso deste workflow por padrão
    allowed_overrides: [workflow, apply_requirements]
    allow_custom_workflows: true

workflows:
  terragrunt-workflow:
    plan:
      steps:
        - run: terragrunt init --terragrunt-non-interactive
        - run: |
            if [ "$COMMENT_ARGS" = "\-\d\e\s\t\r\o\y" ]; then
              echo "⚠️ Iniciando PLAN de DESTRUIÇÃO..."
              terragrunt run-all plan -destroy -out=$PLANFILE --terragrunt-non-interactive
            else
              echo "✅ Iniciando PLAN normal..."
              terragrunt run-all plan -out=$PLANFILE --terragrunt-non-interactive
            fi
        - run: |
            terragrunt show -json $PLANFILE > plan.json
            IC_FILE="infracost-${PULL_NUM}.json"
            infracost breakdown --path=plan.json --format=json --out-file=$IC_FILE
            infracost comment github --path=$IC_FILE \
                                     --repo=$BASE_REPO_OWNER/$BASE_REPO_NAME \
                                     --pull-request=$PULL_NUM \
                                     --github-token=$ATLANTIS_GH_TOKEN \
                                     --behavior=update
            rm $IC_FILE plan.json
    apply:
      steps:
        - run: |
            if [ "$COMMENT_ARGS" = "\-\d\e\s\t\r\o\y" ]; then
              echo "🚮 Executando DESTROY final..."
              terragrunt run-all destroy --terragrunt-non-interactive -auto-approve
            else
              echo "🚀 Executando APPLY normal..."
              terragrunt run-all apply $PLANFILE --terragrunt-non-interactive
            fi